{
  "item.arcane.arcane_shard": "Arcane Shard",
  "item.arcane.arcane_crystal": "Arcane Crystal",
  "item.arcane.eiro_heart": "Heart of Eiro",
  "item.arcane.sair_katana": "Sair's Katana",
  "key.arcane.transform": "Transform",
  "key.categories.arcane": "Arcane",
  "message.arcane.unlocked_sair": "§5Arcane accepted you. Press Alt to become Sair.",
  "message.arcane.unlocked_eiro": "§4The flame of Eiro awakens. Press Alt to show who you are.",
  "message.arcane.power_removed": "§7The power left you.",
  "message.arcane.already_has": "You already have this power",
  "message.arcane.no_power": "You have no power to transform",
  "message.arcane.cooldown": "Transformation on cooldown: %s s",
  "message.arcane.on_sair": "§5You became Sair.",
  "message.arcane.on_eiro": "§4You became Eiro.",
  "message.arcane.off": "§7You returned to your normal form.",
  "message.arcane.not_sair": "The katana obeys only Sair",
  "message.arcane.legend_fell": "§6A legend has fallen! %s defeated %s!",
  "key.arcane.ability": "Ability (throw block)",
  "message.arcane.ability_eiro_only": "This ability needs the Eiro form",
  "message.arcane.ability_cooldown": "Ability on cooldown: %s s",
  "message.arcane.no_block": "Look at a block (within 6 blocks)",
  "message.arcane.bad_block": "This block can't be lifted",
  "item.arcane.fool_card": "Fool's Card",
  "message.arcane.unlocked_jester": "§6The Fool accepted you. Press Alt to transform.",
  "message.arcane.on_jester": "§6You became the Fool.",
  "message.arcane.craft_luck": "§aA luck card empowered the item.",
  "message.arcane.craft_bad": "§cA bad luck card removed %s%% durability.",
  "message.arcane.craft_nothing": "The card had no effect on the item."
}
